# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Awm0wKDMsZMpa1sfnDwTXZz02EB6YOXu
"""

import numpy as np
import pandas as pd
import pandas as pds
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import numpy as np

#uploading files of test and train from drive
train = pds.read_csv('/content/drive/MyDrive/omartrain.csv')
test = pds.read_csv('/content/drive/MyDrive/omartest.csv')

#Using variable for labels.
y = train.Cover_Type

#For functions
X = train.drop('Cover_Type', axis=1)

#Splitting The Data y 20% and x 80%
t_train, t_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
#Proceeding without data normalization to check accuracy

# Logistic Regression
logreg = LogisticRegression()
logreg.fit(t_train, y_train)
Y_pred = logreg.predict(t_test)
acc_log = round(logreg.score(t_train, y_train) * 100, 2)

print("--------------Logistic Regression Model--------------")

print("Linear Classifiers Accuracy =",round(acc_log,2,), "%")
print(Y_pred.shape)
print(Y_pred)
#Exporting columns from dataframe
submission = pds.DataFrame({
        "Id": test["Id"],
        "Cover_Type": Y_pred
    })
submission.to_csv('OmarLogisticRegression_NotNorm.csv', index=False)